USE `purejs_db` ;
DROP TABLE IF EXISTS `main_selector_record`;
DROP TABLE IF EXISTS `main_selector`;
DROP TABLE IF EXISTS `main_relation_record`;
DROP TABLE IF EXISTS `main_relation`;
DROP TABLE IF EXISTS `main_dimension_record`;
DROP TABLE IF EXISTS `main_dimension`;
DROP TABLE IF EXISTS `main_record_value`;
DROP TABLE IF EXISTS `main_user`;
DROP TABLE IF EXISTS `main_record`;

-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 13:31:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema purejs_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema purejs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `purejs_db` DEFAULT CHARACTER SET utf8 ;
USE `purejs_db` ;

-- -----------------------------------------------------
-- Table `purejs_db`.`main_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_record` (
  `mare_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mare_fk_type` INT UNSIGNED NOT NULL,
  `mare_created_on` DATETIME NOT NULL,
  `mare_created_by` VARCHAR(45) NOT NULL,
  `mare_modified_on` DATETIME NULL,
  `mare_modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`mare_id`),
  INDEX `fk_mare_mare_01_idx` (`mare_fk_type` ASC),
  CONSTRAINT `fk_mare_mare_01`
    FOREIGN KEY (`mare_fk_type`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_record_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_record_value` (
  `mava_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mava_fk_record` INT UNSIGNED NOT NULL,
  `mava_fk_dimension` INT UNSIGNED NOT NULL,
  `mava_fk_language` INT UNSIGNED NOT NULL,
  `mava_fk_value` INT UNSIGNED NULL,
  `mava_value` VARCHAR(255) NULL,
  PRIMARY KEY (`mava_id`),
  INDEX `fk_mava_mare_01_idx` (`mava_fk_record` ASC),
  INDEX `fk_mava_mare_02_idx` (`mava_fk_dimension` ASC),
  INDEX `fk_mava_mare_03_idx` (`mava_fk_language` ASC),
  INDEX `key_mava_value` (`mava_value` ASC),
  INDEX `fk_mava_mava_01_idx` (`mava_fk_value` ASC),
  CONSTRAINT `pk_mava_mare_01`
    FOREIGN KEY (`mava_fk_record`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mava_mare_01`
    FOREIGN KEY (`mava_fk_dimension`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mava_mare_02`
    FOREIGN KEY (`mava_fk_language`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mava_mava_01`
    FOREIGN KEY (`mava_fk_value`)
    REFERENCES `purejs_db`.`main_record_value` (`mava_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_dimension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_dimension` (
  `madi_id` INT UNSIGNED NOT NULL,
  `madi_code` VARCHAR(45) NOT NULL,
  `madi_fk_root` INT UNSIGNED NOT NULL,
  `madi_fk_parent` INT UNSIGNED NULL,
  PRIMARY KEY (`madi_id`),
  INDEX `fk_madi_mare_02_idx` (`madi_fk_parent` ASC),
  INDEX `fk_madi_madi_01_idx` (`madi_fk_root` ASC),
  UNIQUE INDEX `key_madi_code` (`madi_code` ASC),
  CONSTRAINT `pk_madi_mare_01`
    FOREIGN KEY (`madi_id`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madi_madi_01`
    FOREIGN KEY (`madi_fk_root`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madi_madi_02`
    FOREIGN KEY (`madi_fk_parent`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_dimension_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_dimension_record` (
  `madr_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `madr_fk_dimension` INT UNSIGNED NOT NULL,
  `madr_fk_record` INT UNSIGNED NOT NULL,
  `madr_order` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`madr_id`),
  INDEX `fk_madr_madi_01_idx` (`madr_fk_dimension` ASC),
  INDEX `fk_madr_mare_01_idx` (`madr_fk_record` ASC),
  CONSTRAINT `fk_madr_madi_01`
    FOREIGN KEY (`madr_fk_dimension`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madr_mare_01`
    FOREIGN KEY (`madr_fk_record`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_relation` (
  `marl_id` INT UNSIGNED NOT NULL,
  `marl_fk_parent_dimension` INT UNSIGNED NOT NULL,
  `marl_fk_child_dimension` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`marl_id`),
  INDEX `fk_marl_madi_01_idx` (`marl_fk_parent_dimension` ASC),
  INDEX `fk_marl_madi_02_idx` (`marl_fk_child_dimension` ASC),
  CONSTRAINT `fk_marl_madi_01`
    FOREIGN KEY (`marl_fk_parent_dimension`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marl_madi_02`
    FOREIGN KEY (`marl_fk_child_dimension`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_marl_mare_01`
    FOREIGN KEY (`marl_id`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_relation_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_relation_record` (
  `marr_id` INT UNSIGNED NOT NULL,
  `marr_fk_relation` INT UNSIGNED NOT NULL,
  `marr_fk_parent` INT UNSIGNED NOT NULL,
  `marr_fk_child` INT UNSIGNED NOT NULL,
  `marr_order` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`marr_id`),
  INDEX `fk_marr_madr_01_idx` (`marr_fk_parent` ASC),
  INDEX `fk_marr_madr_02_idx` (`marr_fk_child` ASC),
  INDEX `fk_marr_marl_01_idx` (`marr_fk_relation` ASC),
  CONSTRAINT `fk_marr_madr_01`
    FOREIGN KEY (`marr_fk_parent`)
    REFERENCES `purejs_db`.`main_dimension_record` (`madr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marr_madr_02`
    FOREIGN KEY (`marr_fk_child`)
    REFERENCES `purejs_db`.`main_dimension_record` (`madr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marr_marl_01`
    FOREIGN KEY (`marr_fk_relation`)
    REFERENCES `purejs_db`.`main_relation` (`marl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_marr_mare_01`
    FOREIGN KEY (`marr_id`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_selector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_selector` (
  `sele_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sele_fk_record` INT UNSIGNED NOT NULL,
  `sele_fk_dimension` INT UNSIGNED NOT NULL,
  `sele_fk_value` INT UNSIGNED NULL,
  `sele_operator` VARCHAR(45) NOT NULL,
  `sele_value` VARCHAR(255) NULL,
  `sele_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sele_id`),
  INDEX `fk_sele_madr_01_idx` (`sele_fk_record` ASC),
  INDEX `fk_sele_madi01_idx` (`sele_fk_dimension` ASC),
  CONSTRAINT `fk_sele_madr_01`
    FOREIGN KEY (`sele_fk_record`)
    REFERENCES `purejs_db`.`main_dimension_record` (`madr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sele_madi01`
    FOREIGN KEY (`sele_fk_dimension`)
    REFERENCES `purejs_db`.`main_dimension` (`madi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_selector_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_selector_record` (
  `sere_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sere_fk_tag` INT UNSIGNED NOT NULL,
  `sere_fk_selector` INT UNSIGNED NOT NULL,
  `sere_fk_record` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sere_id`),
  INDEX `fk_sere_sele_01_idx` (`sere_fk_selector` ASC),
  INDEX `fk_sere_mare_01_idx` (`sere_fk_record` ASC),
  INDEX `fk_sere_mare_01_idx1` (`sere_fk_tag` ASC),
  CONSTRAINT `fk_sere_mare_01`
    FOREIGN KEY (`sere_fk_tag`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sere_sele_01`
    FOREIGN KEY (`sere_fk_selector`)
    REFERENCES `purejs_db`.`main_selector` (`sele_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sere_mare_02`
    FOREIGN KEY (`sere_fk_record`)
    REFERENCES `purejs_db`.`main_dimension_record` (`madr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `purejs_db`.`main_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `purejs_db`.`main_user` (
  `maus_id` INT UNSIGNED NOT NULL,
  `maus_username` VARCHAR(100) NOT NULL,
  `maus_password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`maus_id`),
  CONSTRAINT `pk_maus_mare_01`
    FOREIGN KEY (`maus_id`)
    REFERENCES `purejs_db`.`main_record` (`mare_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
